[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "setiptah-polyglint2d"
description = "A small utility for integration of linear functions over interiors of polygons in 2d"
authors = [
  {name = "Kyle Treleaven", email = "ktreleav@gmail.com"},
]
dynamic = ["version"]
dependencies = [
    "numpy",
]

[project.optional-dependencies]
build = [
    "click",
]
dev = [
    "ipython",
    "scipy",
    "matplotlib",
    "notebook",
    "ipykernel",
]
test = [
    "pytest",
    "pytest-coverage",
]
format = [
    "black",
]
docs = [
    "setiptah-polyglint2d[dev]",
    "nbconvert",
    "mkdocs-material",
    "mkdocs-terminal",
    "mkdocs-rtd-dropdown",
    "mkdocstrings[python]",
    "pymdown-extensions",
]
