name: Deploy Docs

on:
  push:
    branches:
      - mainline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install nox and uv
        run: |
          pip install nox
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Build the docs
        run: nox -s docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/site
          publish_branch: docs-site
          force_orphan: true
